### ISSUE TITLE
using the mod makes no scroll on credit or end poem

### ISSUE THREAD

**Issue by GodlyFirecracker** [atikiNBTW/Return-Dirt-Background#4]
How to fix
like this:
Permit the background texture overlay file to scroll in this situation. Perhaps introduce a different texture overlay file for the credits background as to not cause any conflicts? This texture could even be animated as to emulate scrolling.
or any

**Comment by atikiNBTW** [comment]
I'll check when I have time, thanks for the issues.

**Comment by GodlyFirecracker** [comment]
ok,pls check aswell the https://github.com/atikiNBTW/Return-Dirt-Background/issues/3 later

**Comment by atikiNBTW** [comment]
should be fixed in latest release, pls check and close the issue if it's fixed

**Comment by GodlyFirecracker** [comment]
i checked and its fixed,there will be only around 2-3 more bugs at most,reporting it later,and its different than previous
