### ISSUE TITLE
Upload `gradlew` and `gradlew.bat` to GitHub

### ISSUE THREAD

**Issue by Lightningtow** [atikiNBTW/Return-Dirt-Background#7]
Generally when uploading code to a VCS, it's very helpful to make sure the files `gradlew` (no filename extension) and `gradlew.bat` are uploaded, along with the folder `gradle`. The folder is there but the gradlew files aren't, which makes it difficult for people to build from scratch. It's possible they got added to the `.gitignore` .
Having those two files and the folder lets others can download your code and immediately build your project with the same gradle distribution as you, without needing to manually install the correct version of gradle on their system.

Thank you!
-Light

**Comment by atikiNBTW** [comment]
fixed with latest release
